### PR TITLE
Fixing API reference

### PR DESCRIPTION
**Pull request by NoraLoose**
This PR fixes the docstrings of the roms-tools classes so that they show up nicer in the API reference. It also adds docformatter to pre-commit, and adds pre-commit to the docs environment.

### CODE REVIEW

**Comment by NoraLoose** [comment]
@dafyddstephenson I added `docformatter` to pre-commit, but there is an issue:
https://github.com/CWorthy-ocean/roms-tools/actions/runs/11411703114/job/31756447960?pr=170

Have you seen this before?  Strange because I'm using the same version for pre-commit-hooks and docformatter as C-Star.

Looks like this is a known issue: https://github.com/PyCQA/docformatter/issues/293

**Comment by dafyddstephenson** [comment]
sorry, apparently my email app was closed and I didn't notice - I do recognise this , I got around it by pinning the version of pre-commit to 3.8: (https://github.com/CWorthy-ocean/C-Star/blob/main/.github/workflows/pre-commit.yaml).

**Comment by NoraLoose** [comment]
Thanks @dafyddstephenson!

**Comment by NoraLoose** [comment]
@dafyddstephenson should we pin the pre-commit version here as well?
https://github.com/CWorthy-ocean/C-Star/blob/47de1ebd5ff70f92c52beff1f1bc7f796029ebc0/ci/environment.yml#L16

**Pull request merged**
